[2025-05-08T12:20:03.767+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-08T12:20:03.780+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.weather_dag_1 scheduled__2025-05-08T12:15:00+00:00 [queued]>
[2025-05-08T12:20:03.787+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.weather_dag_1 scheduled__2025-05-08T12:15:00+00:00 [queued]>
[2025-05-08T12:20:03.787+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-05-08T12:20:03.811+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): weather_dag_1> on 2025-05-08 12:15:00+00:00
[2025-05-08T12:20:03.817+0000] {standard_task_runner.py:72} INFO - Started process 37352 to run task
[2025-05-08T12:20:03.825+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag', 'weather_dag_1', 'scheduled__2025-05-08T12:15:00+00:00', '--job-id', '175', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpcfvbwj86']
[2025-05-08T12:20:03.831+0000] {standard_task_runner.py:105} INFO - Job 175: Subtask weather_dag_1
[2025-05-08T12:20:03.869+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_dag.weather_dag_1 scheduled__2025-05-08T12:15:00+00:00 [running]> on host codespaces-16c72d
[2025-05-08T12:20:03.961+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='weather_dag_1' AIRFLOW_CTX_EXECUTION_DATE='2025-05-08T12:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-08T12:15:00+00:00'
[2025-05-08T12:20:03.962+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-08T12:20:03.982+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-05-08T12:20:03.983+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'bash /workspaces/airflow/dags/wrapper.sh ']
[2025-05-08T12:20:03.994+0000] {subprocess.py:99} INFO - Output:
[2025-05-08T12:20:03.998+0000] {subprocess.py:106} INFO - /workspaces/airflow/dags/wrapper.sh: line 2: weather/bin/activate: No such file or directory
[2025-05-08T12:20:04.502+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-05-08T12:20:04.502+0000] {subprocess.py:106} INFO -   File "/workspaces/airflow/dags/weather_data.py", line 4, in <module>
[2025-05-08T12:20:04.503+0000] {subprocess.py:106} INFO -     import pyt
[2025-05-08T12:20:04.503+0000] {subprocess.py:106} INFO -     ^^^^^^^^^^
[2025-05-08T12:20:04.503+0000] {subprocess.py:106} INFO - ModuleNotFoundError: No module named 'pyt'
[2025-05-08T12:20:04.567+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-05-08T12:20:04.573+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-08T12:20:04.578+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_dag, task_id=weather_dag_1, run_id=scheduled__2025-05-08T12:15:00+00:00, execution_date=20250508T121500, start_date=20250508T122003, end_date=20250508T122004
[2025-05-08T12:20:04.598+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-08T12:20:04.599+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 175 for task weather_dag_1 (Bash command failed. The command returned a non-zero exit code 1.; 37352)
Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-08T12:20:04.639+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-08T12:20:04.652+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-08T12:20:04.652+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
